### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by jordi3d** [alknopfler/alkalarm#11] opened 2020-04-18 16:50 UTC
Even I get a success message on termination of the install.sh script, it does not install properly the go script, and the webserver/webpage neither.
Not sure how to solve the deprecated DefaultCredentials in the go file.
After that, I also get sqlite error messages.
Tried many times following the wiki instructions with no success

**Comment by alknopfler** [comment] 2020-04-18 18:00
As you can imagine, I need more information in order to help with the issue.

Could you give the next information :

- hardware you are using, and the Operating system 
- the install.sh output that you are getting and the information you are providing (except the pass)

**Comment by jordi3d** [comment] 2020-04-18 18:34
Uname -a output is:
Raspberry 4.19.66-v7+ armv71 

Hardware is a Raspberry Pi 3 Model B+

First I get is a message of GOBIN no set
And despite that, I get success message...

I repeat the installation setting it with:
GOBIN=/home/pi/alkalarm/go/bin/
export GOBIN



PS: I am a veteran computer scientist, veteran means I am 53 yo and not programming seriously since many years, just some Javascript & PHP.
I worked for Sun Microsystems in support services and before that, developed some cshell scripts in SGI Irix in the 90’s, but after this said, I am not expert at all with Raspi/linux environment.

PPS: I mist go pock up my wife (nurse) at the hospital now. Will send you the full output of the install script later on tonight. Thanks for your help.

Отправленные с моего айфоне

**Comment by jordi3d** [comment] 2020-04-18 19:27
One more thing:
My golang did not like the declaration:

type DefaultCredentials = Credentials

I had to replace all DefaultCredentials appearing (4 if I am not wrong in config.go if I remember well) by Credentials to clear the error.
I suppose it is wrong to do that.

Отправленные с моего айфоне

**Comment by jordi3d** [comment] 2020-04-18 19:30
Hi Al,
I will send you the ./install.sh | tee output.file (minus the password), when I am back home.
Now I am outside at the elder residence waiting for my wife to quit her 12h job

Отправленные с моего айфоне

**Comment by jordi3d** [comment] 2020-04-18 21:49
﻿stderr output

**Comment by jordi3d** [comment] 2020-04-18 21:52
﻿﻿stderr output

**Comment by alknopfler** [comment] 2020-04-19 07:13
Could you please paste also the standard output? 
Do you verify if you have information after the installation in /opt/alkalarm?
I suggest review all the steps (step by step checking if the output directory is correct) you are looking into the installation script  to figure out where is the problem.
Are you using a release or máster branch?

**Comment by alknopfler** [comment] 2020-04-19 07:20
Just to discard, please try the installation phase with the release v2.3.2
This version is older without any oauth and alexa but the installation is easier than the latest

**Comment by jordi3d** [comment] 2020-04-19 09:23
Sorry to not know the answer.
As I said, I am just a beginner in Raspi.
I executed: 
Git clone https://github.com/alknopfler/alkalarm.git

I am preparing the stdout and will send you in a few minutes


Отправленные с моего айфоне

**Comment by jordi3d** [comment] 2020-04-19 09:23
Ok will try after sending you the stdout


Отправленные с моего айфоне

**Comment by jordi3d** [comment] 2020-04-19 09:32
It looks like I have same files under /opt/alkalarm


Отправленные с моего айфоне

**Comment by jordi3d** [comment] 2020-04-19 09:41
Here it is the stdout.

Thanks for your support.

**Comment by jordi3d** [comment] 2020-04-19 10:06
Installed 2.3.2
Got this error message



Отправленные с моего айфоне

**Comment by jordi3d** [comment] 2020-04-19 10:18
After installing 2.3.2. got the message: "Please enter your access code"
The Admin password I introduced does not grant access... null password neither
I guess this is related to the error message I got when installing this version...
undefined: config.WEBACCESS_PASS

**Comment by alknopfler** [comment] 2020-04-19 12:07
> Installed 2.3.2 Got this error message Отправленные с моего айфоне
> […](#)

Sorry but I cannot see the output...do you paste here?

**Comment by jordi3d** [comment] 2020-04-19 12:31
Ok, will do it again


Отправленные с моего айфоне

**Comment by jordi3d** [comment] 2020-04-19 12:34
[31m
        _ _         _
       | | |       | |
   __ _| | | ____ _| | __ _ _ __ _ __ ___
  / _  | | |/ / _  | |/ _  | '__| '_   _  | (_| | |   < (_| | | (_| | |  | | | | | |
  \__,_|_|_|\_\__,_|_|\__,_|_|  |_| |_| |_|

[32mStarting the installation...Please press a key:
(B[m[32m
### Installing packages ... ###
(B[m
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]
Hit:3 http://apt.pilight.org stable InRelease
Hit:4 http://apt.pilight.org nightly InRelease
Fetched 25.4 kB in 1s (14.5 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python-dev is already the newest version (2.7.13-2).
pigpio is already the newest version (1.64-1).
python-pigpio is already the newest version (1.64-1).
python-pip is already the newest version (9.0.1-2+rpt2).
python3-pigpio is already the newest version (1.64-1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
go/
*****
*****
*****
*****
[32m
### Creating Folders ... ###
(B[m
/opt/alkalarm exists!
/var/tmp/alkalarm exists!
/var/log/alkalarm exists!
[32m
### Creating the email smtp server account ... ### 
(B[m[32m
### Creating the password file with email smtp server password ... ### 
(B[m[32m
### Creating the accounts to use the alarm system ... ### 
(B[m[32m
### Creating the domain for the webserver ... ### 
(B[m[32m
### Copy the python script and binary to the project directory ... ### 
(B[m
[32m
### Installing web server and copy the binary to the project directory ... ###
(B[m
[32m
### Installing the discovery codes utility and copy the binary to the project directory ... ###
(B[m
[32m
### Creating the file in rsyslog ###
(B[m
[32m
### Enabling the PiGPIO daemon ###
(B[m
[32m
### Creating and starting AlkAlarm systemd service ###
(B[m
[32m
### Creating and starting webserver systemd service ###
(B[m
[32m
### End Of Installation...SUCCESS ###
(B[m

**Comment by jordi3d** [comment] 2020-04-19 12:40
errors I got after installing 2.3.2

creating domain for the webserver:
cp: cannot create regular file 'opt/alkalarm/webinterface/webserver' text file busy

copy python:
alkalarm.go:48: undefined config.WEBACCESS_PASS
cp -r not specified; omitting directory '/root/bin/alkalarm'

installing webserver:
cp -r not specified: omitting directory '/root/bin/webserver'

installing discovery codes:
cp -r not specified: omitting directory '/root/bin/discoveryCodes'

***
***
***
End of instalation... SUCCESS ###

**Comment by alknopfler** [comment] 2020-04-19 12:53
Ok, try to do a clean installation. To do that, stop the services (alkalarm and alkalarm-webserver) before installing the 2.3.2, and  you must remove the directories and their content also before install ing again

```
Systemctl stop alkalarm
Systemctl stop alkalarm-webserver
Rm -fr /opt/alkalarm
Rm -fr /var/log/alkalarm
Rm -fr /var/tmp/alkalarm
```

After that, install again the 2.3.2

**Comment by jordi3d** [comment] 2020-04-19 13:01
thanks. Doing now,,,

**Comment by jordi3d** [comment] 2020-04-19 13:06
same errors ... except the first one of file busy...

copy python:
alkalarm.go:48: undefined config.WEBACCESS_PASS
cp -r not specified; omitting directory '/root/bin/alkalarm'

installing webserver:
cp -r not specified: omitting directory '/root/bin/webserver'

installing discovery codes:
cp -r not specified: omitting directory '/root/bin/discoveryCodes'



I am going to launch it anyway and see if there is any progress...

**Comment by jordi3d** [comment] 2020-04-19 13:08
both services started without any error message:
alkalarm
alkalarm-webserver

**Comment by jordi3d** [comment] 2020-04-19 13:19
nothing seemed to start the webserver when going to http://localhost

So I went into /opt/alkalarm/webinterface 
there I executed: go run webserver.go
Got the message: listening... :80

The html page now is shown, but I still get the message of 
127.0.0.1
Please enter your access code:

and none of the used during install (for smtp account or for admin) are accepted as correct when requesting access
NULL (intro) neither
0000 neither
admin neither

**Comment by jordi3d** [comment] 2020-04-19 13:22
I've seen now there is in plain text the password I typed in, on file .passACCESS
So I am sure there is no typo in writing it

**Comment by alknopfler** [comment] 2020-04-19 13:23
Let's go step by step:
0-. Remove content as I said before again, and stop the services (repeat this phase if you need to re-install to get a clean environment)
Now, go into the main folder alkalarm (don't run absolutely the script). I mean, cd alkalarm -> ./install.sh (inside the folder)
1-. First verify that /opt/alkalarm/.userSMTP containt your input information (doing cat file is enough)
2-. same with /opt/alkalarm/.passSMTP (don't give me the pass because is clear text)
3-. Same with /opt/alkalarm/.passACCESS (this is the password to access, remember for next steps)
Tell me if you're getting the same "cp -r" error.

If you're having this error, is imposible to access the webserver because the files are not in their site.

**Comment by jordi3d** [comment] 2020-04-19 13:24
Ok. Thanks again.

**Comment by alknopfler** [comment] 2020-04-19 13:25
The problem is that the instllation script is not copying the files, so, the server start with a null configuration (the cp -r is exatly to create the alkalarm configuration, so if this phase fails, you cannot access with your information).

The good new is that I have all the information now to help you. Let's go step by step

**Comment by jordi3d** [comment] 2020-04-19 13:36
In the install manual does not say this, but I see on the screen capture a root@raspberrypi when launching install.sh
I've done until now this way, so it is OK if I install this way? I guess so, install with superuser rights...

I will reboot my raspi now...
login in raspi with the pi user
On prompt:
sudo -i 
cd /home/pi/alkalarm
./install.sh
Then I will check if in the hidden files, there is the info I introduced...
I will record all this in video... just in case...

**Comment by jordi3d** [comment] 2020-04-19 13:48
Same errors with cp -r
hidden files have exactly the info I typed in.

I have the video... if you want to see it, I can send you through wetransfer
you have my email right? Tell me where to send the wetransfer

**Comment by jordi3d** [comment] 2020-04-19 13:54
I think it is trying to install alkalarm in the root directory
Maybe I have made a mistake and should not do sudo -i? and only sudo? before install?

**Comment by alknopfler** [comment] 2020-04-19 14:02
Try sudo -s

**Comment by alknopfler** [comment] 2020-04-19 14:09
Anyway, I'm installing and older Raspi with your hardware configuration, in order to figure out why you're getting this error. Maybe the sudo -s could fix the problem, but I'm getting up my old raspby in order to have the same hardware and environment than you.
For sure, the golang installation should be done by root, because the binary file will be in /root/bin/alkalarm and /root/bin/webserver

**Comment by jordi3d** [comment] 2020-04-19 14:37
in my case, golang is in /home/pi/alkalarm/go/
sudo -s
cp: cannot stat '/root/bin/webserver': No such file or directory

**Comment by alknopfler** [comment] 2020-04-19 14:52
When you repeat the steps for the installation as root, if you see into the script.sh there's an line which is "go install alkalarm" and the result of that is a binary file located in /root/bin/alkalarm if you have done by root with sudo -s. 
With the copy command (where you're having problems), you move the result of this binary to the correct site.

Said that, you can follow the script instruction in order to do manually (one by one) copying the files to the correct site if you are having problems instead of running automatically with the install.sh script. The install.sh script is just a help to do automatically, but you can do manually with the same result.

**Comment by jordi3d** [comment] 2020-04-19 15:26
I've manually copied the files you mention, and now there is only one error messages remaining at install, 

alkalarm.go:48 undefined: config.WEBACCESS_PASS

I had to copy to /root/bin the files _433.py, alkalarm, discoverCodes and webserver

**Comment by jordi3d** [comment] 2020-04-19 15:30
at /etc/init.d do not appear any alkalarm* service
despite starting the service issuing the systemctl start alkalarm and alkalarm-webservice commands

**Comment by jordi3d** [comment] 2020-04-19 15:33
password is not accepted from the webserver landing page

**Comment by alknopfler** [comment] 2020-04-19 15:56
> at /etc/init.d do not appear any alkalarm* service
> despite starting the service issuing the systemctl start alkalarm and alkalarm-webservice commands

It's normal, it's done by systemctl daemon. /etc/initd folder is not used nowadays. You have to use systemctl as I said before ;)

**Comment by alknopfler** [comment] 2020-04-19 15:58
> password is not accepted from the webserver landing page

It's due to the fail in the webserver. This installation should be straight forward in most cases. I don't know why you're getting all this issues

**Comment by jordi3d** [comment] 2020-04-19 15:59
it is fine to write "localhost" as name for the server?
Or it is better to put 127.0.0.1 or even better the IP given by my router?
Does this affect to my issues?

**Comment by alknopfler** [comment] 2020-04-19 16:00
In my deployment I always put localhost

**Comment by alknopfler** [comment] 2020-04-19 16:09
I guess is something incompatible with the code... Sound very strange for me. I did right now in a new raspby (the older one) and it works fine.

The code in alkalarm.go 48 it's pretty simple. it's just to access to a variable that is established in the config file. Are you using the 2.3.2 version? this is Did you remove the previous code? It's sound like you're getting a mix with different version of configuration files . 

To be honest, I don't know how to solve it without hand-on directly

**Comment by jordi3d** [comment] 2020-04-19 16:11
so to summarize:
I had to set the GOBIN environment variable to point to go/bin that is under /home/pi/alkalarm
export that variable
I removed any previous trace of alkalarm in my raspi and executed a clean install of 2.3.2, using sudo -s
Got some cp error messages, and circumvented them by manually copying the 4 files (webserver, discoverCodes, alkalarm and _433.py) into /root/bin
When reinstalling again, all error messages of cp are gone, except:

alkalarm.go:48 undefined: config.WEBACCESS_PASS

I am able to launch the services for alkalarm and alkalarm-webserver
When launching the webbrowser, requests me a password, and despite matching the one at .passACCESS, it doesn't give access

stuck here at this point.

**Comment by jordi3d** [comment] 2020-04-19 16:13
how I can double check that I am using v2.3.2?
I went to the git repository and looked for the 2.3.2
All files installed are dated on October 6 2018 once decompressed

**Comment by alknopfler** [comment] 2020-04-19 16:15
The reason that you cannot access to the landing web is because the alkalarm.go:48 cannot set the pass that you have in the .pass file into the database to grant you access
Why? I don't know my friend...it's quite strange 

Let me try a  ubuntu installation from scratch with the 2.3.2 code, saving the session to show you the process. But, I will need a little more time to prepare everything, ok?

**Comment by jordi3d** [comment] 2020-04-19 16:16
do you want to see the video I recorded while installing?
maybe you can see something I am missing
Tell me where to send the link to the wetransfer... don't know it this is public or just you and me

**Comment by alknopfler** [comment] 2020-04-19 16:18
> how I can double check that I am using v2.3.2?
> I went to the git repository and looked for the 2.3.2
> All files installed are dated on October 6 2018 once decompressed

yes, if you see this date, you're in the right version. Remember, the master release is ok, but it's more complex so I recommended to start with the stable 2.3.2 before going with the alexa integration and oauth with google. 
I'm gonna install a blank ubuntu, from scratch using the 2.3.2 

PS: send the video link to alknopfler@gmail.com

**Comment by jordi3d** [comment] 2020-04-19 16:19
will do in a moment... forgive slowness typing, I was holding the camera with the other hand ;-)

**Comment by jordi3d** [comment] 2020-04-19 16:22
sent. I hope you see some mistake I might be doing...

**Comment by jordi3d** [comment] 2020-04-19 16:25
you know, it's been at least 1 year since I tried to get your code up&running.
But I was very busy, so I could dedicate some time some weekend I was not out.
Never tried to contact you and opening an issue - my fault.
Until I was pretty sure I was doing everything I could on my side, I decided to not reach you. 
Thanks for your help, it would have been a lot quicker if I asked you first!

**Comment by alknopfler** [comment] 2020-04-19 17:26
Hi again, After watching your video, I guess that I know the root of the problem. 
The new golang version 1.11 has a different path routing src and binary in a different way being incompatible with glide (deprecated). The code was written years ago, and now the glide is deprecated as well as the path with the 1.11 go release. That's the reason why the environment cannot set properly, as well as why you cannot finish the installation. Even without glide, I guess you could have some new errors. In my raspby works fine because the golang ecosystem is stable and the alarm system has not been updated for a long time (to be honest, since I created the system). 

Definitely, I need time to fix it creating and forcing versions and also creating a new installer with your feedback. I'll send you a notice here when I finish the new assistant

I'm gonna label like a bug but a new release with all the features as well as the new installer will be released soon. 
Thanks for your feedback again ;)

**Comment by jordi3d** [comment] 2020-04-19 17:36
I'm happy to have been useful and not feeling so bad about my skills :-)
Looking forward to your updates. 
Please remember to set GOBIN vars in the installer :-) it's been a nightmare.

**Comment by alknopfler** [comment] 2020-04-19 17:39
Yes, I'm thinking about creating directly here the binary to download for a verison of raspberry instead of do everything with golang building the binary.

**Comment by alknopfler** [comment] 2020-04-19 18:12
It's gonna be much easier because I'm gonna build in each release the binary for alkalarm and the webserver, just to run the install.sh script to prepare the environment, but in that case, without the golang phase to avoid all the problems that you've been having. 

Let's a couple of days to prepare a new release available, and if you are available, test the previous version (beta)

**Comment by jordi3d** [comment] 2020-04-19 18:35
Count on me for the first beta!!


Отправленные с моего айфоне

**Comment by alknopfler** [comment] 2020-04-19 20:12
Hi my friend! I've got the first beta available for you.
Please follow the next instructions:
1-. Remove the alkalarm git folder from your home
2-. stop services and delete the folders mentioned before in this issue (/opt/alkalarm, /var/log/alkalarm and /var/tmp/alkalarm)
3-. git clone https://github.com/alknopfler/alkalarm.git again
4-. cd alkalarm
5-. git checkout v.2.3.3 (to change to the beta release candidate branch)
6-. execute the install.sh script again 

PS: the wiki doc is changed also with your feedback regarding to the installation. No more golang is needed.
PSS: confirm the status in order to do a pull request to master branch and deliver the 2.x.x release after your verification with this beta branch

**Comment by jordi3d** [comment] 2020-04-19 21:28
Mixed news for you:
The app installed flawlessly... good job!!!
However, when launching the browser, still requests the password and does not recognize it.
The .passACCESS file is at /opt/alkalarm
so I am sure I am not writing a typo...
I must go sleep in 30min, tomorrow will follow up if you don’t mind.
Thanks for your awesome and quick support

Отправленные с моего айфоне

**Comment by alknopfler** [comment] 2020-04-19 21:39
ok, try 1234 as password

**Comment by jordi3d** [comment] 2020-04-19 21:47
I got up from bed to try it :-)
Nope, it does not work with 1234 and with my password neither.
Maybe some sqlite3 misconfiguration on my side?
Will continue tomorrow.
It’s almost midnight here in Spain and must wake up at 7:30am tomorrow


Отправленные с моего айфоне

**Comment by alknopfler** [comment] 2020-04-20 12:59
Did you stop the services and remove the (rm -fr /opt/alkalarm)  ??? I've been testing severals time with different password and every time is working fine

In that case, coud you paste the output of the install.sh ?

**Comment by jordi3d** [comment] 2020-04-20 14:17
Yes, I stopped the services and removed all traces of allalarm in my raspi
I will record a video again so maybe you can see what I am not doing right.


Отправленные с моего айфоне

**Comment by alknopfler** [comment] 2020-04-20 16:34
The video shows that you're not getting the database ready in /opt/alkalarm. I'm gonna checking out with some tests in my environment. In my case when I remove the /opt/alkalarm, the database file appears automatically when I start the service the first-time.

**Comment by alknopfler** [comment] 2020-04-20 16:48
I mean, for example, with a new scratch install.sh phase I get the next ls /opt/alkalarm output:
1-. Rm the folders (included /opt/alkalarm, so doesn't exist)
2-. stop services
3-. launch install.sh
4-. the output of 'ls /opt/alkalarm' is:
total 12192
drwxr-xr-x 7 root root     4096 abr 20 18:45 ..
-rw-r--r-- 1 root root       22 abr 20 18:45 .userSMTP
-rw-r--r-- 1 root root       10 abr 20 18:45 .passSMTP
-rw-r--r-- 1 root root       10 abr 20 18:45 .passACCESS
drwxr-xr-x 4 root root     4096 abr 20 18:46 webinterface
-rw-r--r-- 1 root root     9395 abr 20 18:46 _433.py
-rwxr-xr-x 1 root root 10085404 abr 20 18:46 alkalarm
-rwxr-xr-x 1 root root  2450320 abr 20 18:46 discoverCodes
**-rw-r--r-- 1 root root    45056 abr 20 18:46 data.db**
-rw-r--r-- 1 root root     9731 abr 20 18:46 _433.pyc
drwxr-xr-x 3 root root     4096 abr 20 18:46 .

So when I start the browser I can access with the password that I set without any errors. So I'm sure that your problem is that the database is not been created. Now I have to know why is not creating the database. 

Could you paste the log file /var/log/alkalarm ??? After installation, you could use the log to what is happening...

**Comment by jordi3d** [comment] 2020-04-20 17:03
GLIBC_2.28 not found and required!

**Comment by jordi3d** [comment] 2020-04-20 17:14
it is OK if I execute:
apt-get update && apt-get upgrade libc6?

if I get any suggestion, say Yes to continue?

**Comment by jordi3d** [comment] 2020-04-20 17:15
looks like I have installed 2.24-11+deb9u4
Not sure why... should be default one?

**Comment by alknopfler** [comment] 2020-04-20 17:21
> it is OK if I execute:
> apt-get update && apt-get upgrade libc6?
> 
> if I get any suggestion, say Yes to continue?

yes I guess you have to do the upgrade. 
Is working after that?

**Comment by jordi3d** [comment] 2020-04-20 17:24
it is taking a while this upgrade, I'll let you know

**Comment by jordi3d** [comment] 2020-04-20 17:35
looks like I have raspbian stretch, is that a problem?
Still not generating de data.db file, nor the _433.pyc file in /opt/alkalarm

**Comment by alknopfler** [comment] 2020-04-20 17:39
Did you restart the services? Please, remove logs and restart service and tell me what happen

**Comment by jordi3d** [comment] 2020-04-20 17:40
I did
Will do it again and restart the raspi

**Comment by jordi3d** [comment] 2020-04-20 17:41
same error messages about GLIBC_2.28 not found

**Comment by alknopfler** [comment] 2020-04-20 17:41
The error with glic is the same?

**Comment by jordi3d** [comment] 2020-04-20 17:43
yes
I am restarting now

**Comment by jordi3d** [comment] 2020-04-20 17:50
same error in log file GLIBC_2.28 not found after removing, restarting and reinstalling
Did any upgrade at all the system?
not sure what else I can do... will try to upgrade again...

**Comment by jordi3d** [comment] 2020-04-20 17:52
doing a sudo dpkg -l | grep libc it says I still have 2.24-11!!

**Comment by jordi3d** [comment] 2020-04-20 18:04
no way to upgrade to GLIBC_2.28 ... any hint?

**Comment by jordi3d** [comment] 2020-04-20 18:05
do I need to install sqlite3 or something?

**Comment by jordi3d** [comment] 2020-04-20 18:06
ldd --version
I get GLIBC 2.24-11+deb9u4

**Comment by jordi3d** [comment] 2020-04-20 18:07
it says it is the newest libc6

**Comment by jordi3d** [comment] 2020-04-20 18:09
it might be related to the version of linux installed in my raspi?
maybe I need to upgrade to buster?

**Comment by jordi3d** [comment] 2020-04-20 18:09
looks like I have debian stretch, I don't know why

**Comment by jordi3d** [comment] 2020-04-20 18:12
I am upgrading firmware and will try to install Raspian Buster

**Comment by alknopfler** [comment] 2020-04-20 18:20
> do I need to install sqlite3 or something?

No no

**Comment by alknopfler** [comment] 2020-04-20 18:22
> I am upgrading firmware and will try to install Raspian Buster

Ok my friend...

**Comment by jordi3d** [comment] 2020-04-20 18:24
depmod 4.19.115-v7+
up from 4.19.66-v7+
will continue with the process and will try the install again... will update you with results.

**Comment by jordi3d** [comment] 2020-04-20 18:50
still installing the upgrade... is taking a while...
I see references to libc6:armhl 2.28-10+rpi1 finally!!!
Will post with the outcomes

**Comment by jordi3d** [comment] 2020-04-20 21:05
Finally, everything looks fine!
I had to first upgrade raspi firmware and then upgrade from stretch to buster version of raspbian
Install went flawlessly, data file created, and password accepted.
Do you suggest to install last version of alkalarm or this one is fine?
I don't plan to use alexa at all... at least not for now.

Will start trying to configure my sensors and see if I can manage to have my alarm working soon.
Thanks for your amazing support!
In case someone has similar problem to mine:
https://pimylifeup.com/upgrade-raspbian-stretch-to-raspbian-buster/
Best,
J.

**Comment by alknopfler** [comment] 2020-04-21 06:44
Good news!!! If you don't have the idea to use alexa, this version is the best one for you.

Thanks again for your feedback to improve the installation phase.
I will close the bug updating the info in the wiki  about raspberry version.

**Closed as completed** 2020-04-21 06:45 UTC
Labels: bug, enhancement

**Comment by jordi3d** [comment] 2020-04-21 08:46
At this moment, I am trying to pair sensors (door, window, movement), but I am not being very lucky.
Only the remote command is working/being detected.
Will keep experimenting and will ask for help later on.
Thanks again!!

Отправленные с моего айфоне

**Comment by alknopfler** [comment] 2020-04-21 16:38
A trick, you could scan sensors using the webui, but also you can scan directly in command line using the_433.py python script.
Remember only 433mhz sensors

**Comment by jordi3d** [comment] 2020-04-21 16:55
with RFSniffer I can read the sensors I have:
http://azsecurity.net/Productos/sensor-magnetico-de-puerta-mc-03b/

with my raspi sensors:
https://es.aliexpress.com/item/32467257826.html 
<https://es.aliexpress.com/item/32467257826.html?src=google&src=google&albch=shopping&acnt=494-037-6276&isdl=y&slnk=&plac=&mtctp=&albbt=Google_7_shopping&aff_platform=google&aff_short_key=UneMJZVf&&albagn=888888&albcp=8698529884&albag=87458843957&trgt=743612850874&crea=es32467257826&netw=u&device=c&albpg=743612850874&albpd=es32467257826&gclid=Cj0KCQjws_r0BRCwARIsAMxfDRjan5BfRSgiT0TRYDI0CBtpDlMhjjDC_wTSJ1l06XSKaL5WsBThkI8aApZHEALw_wcB&gclsrc=aw.ds>

with your app, only the remote command works for now...

will dedicate more time tomorrow... I have got a job assignment today...

Thanks!
